/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package crosswordgame;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import javax.swing.DefaultListModel;

/**
 *
 * @author Sean
 */
public class AdminPanel extends javax.swing.JPanel {

    private UserData selectedUser;
    private crossGame selectedGame;
    private StatisticsData selectedStats;
    private DefaultListModel userListModel;
    private DefaultListModel statsListModel;
    private DefaultListModel gameListModel;
    
    public AdminPanel() {
        initComponents();
        setMinimumSize(getPreferredSize());
           setMaximumSize(getPreferredSize());
 
           userListModel=new DefaultListModel();
           statsListModel=new DefaultListModel();
           gameListModel=new DefaultListModel();
           userJList.setModel(userListModel);
           statsJList.setModel(statsListModel);
           gameJList.setModel(gameListModel);
           createUserList();
        
        
         statsScoreText.setEnabled(false);
       deleteStatsButton.setEnabled(false);
       editStatsButton.setEnabled(false);
       saveStatsButton.setEnabled(false);
      statsScoreText.setEnabled(false);
      dateText.setEnabled(false);
    AModText.setEnabled(false);
    BModText.setEnabled(false);
    deleteSavedGameButton.setEnabled(false);
         editSaveGameButton.setEnabled(false);
         saveGameChangesButton.setEnabled(false);
         userNameText.setEnabled(false);
     passwordText.setEnabled(false);
     saveUserButton.setEnabled(false);
       deleteUserButton.setEnabled(false);
       editUserButton.setEnabled(false);
        
    }
    
    private void createUserList(){
            userListModel.clear();
            File directory = new File("./userdata");  
            File[] files = directory.listFiles(); 
            if(files.length>0){
            for (int index = 0; index < files.length; index++)  
            {  
                userListModel.addElement(files[index].getName());  
            }
             
            }
    }
    private void createGameList(){
            gameListModel.clear();
            if(selectedUser.savedGames.size()>0){
            for (int index = 0; index < selectedUser.savedGames.size(); index++)  
            {  
                gameListModel.addElement(selectedUser.savedGames.get(index).name);  
            }
            }
   
             
    dateText.setText("");
    AModText.setText("");
    BModText.setText("");
    dateText.setEnabled(false);
    AModText.setEnabled(false);
    BModText.setEnabled(false);
    }
    
    private void createStatsList(){
        statsListModel.clear();
            if(selectedUser.stats.size()>0){
            for (int index = 0; index < selectedUser.stats.size(); index++)  
            {  
                statsListModel.addElement(selectedUser.stats.get(index).gamename);  
            }
    }
             
       statsScoreText.setText("");
        statsScoreText.setEnabled(false);
       deleteStatsButton.setEnabled(false);
       editStatsButton.setEnabled(false);
       saveStatsButton.setEnabled(false);
      statsScoreText.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userJList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        deleteUserButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameJList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        statsJList = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editUserButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AModText = new javax.swing.JTextField();
        BModText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dateText = new javax.swing.JFormattedTextField(new SimpleDateFormat("MM:dd:yyyy HH:mm:ss"));
        deleteSavedGameButton = new javax.swing.JButton();
        editSaveGameButton = new javax.swing.JButton();
        saveGameChangesButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        statsScoreText = new javax.swing.JTextField();
        deleteStatsButton = new javax.swing.JButton();
        editStatsButton = new javax.swing.JButton();
        saveStatsButton = new javax.swing.JButton();
        saveUserButton = new javax.swing.JButton();

        userJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userJList);

        jLabel1.setText("User List");

        deleteUserButton.setText("Delete");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });

        gameJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        gameJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                gameJListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(gameJList);

        jLabel2.setText("Saved Game List");

        jLabel3.setText("User Information");

        jLabel4.setText("Game Information");

        jLabel5.setText("Username:");

        jLabel6.setText("Password:");

        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        statsJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        statsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                statsJListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(statsJList);

        jLabel7.setText("Statistics List");

        jLabel8.setText("Statistics Information");

        editUserButton.setText("Edit");
        editUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Score Modifiers");

        jLabel10.setText("A:");

        jLabel11.setText("B:");

        jLabel12.setText("Start Date:");

        deleteSavedGameButton.setText("Delete");
        deleteSavedGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSavedGameButtonActionPerformed(evt);
            }
        });

        editSaveGameButton.setText("Edit");
        editSaveGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveGameButtonActionPerformed(evt);
            }
        });

        saveGameChangesButton.setText("Save");
        saveGameChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameChangesButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Score:");

        deleteStatsButton.setText("Delete");
        deleteStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStatsButtonActionPerformed(evt);
            }
        });

        editStatsButton.setText("Edit");
        editStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStatsButtonActionPerformed(evt);
            }
        });

        saveStatsButton.setText("Save");
        saveStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveStatsButtonActionPerformed(evt);
            }
        });

        saveUserButton.setText("Save");
        saveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(statsScoreText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(passwordText))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(saveUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleteUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(deleteStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveStatsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(AModText)
                                                            .addComponent(BModText, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(deleteSavedGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editSaveGameButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(saveGameChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(deleteUserButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editUserButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveUserButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(AModText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(BModText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteSavedGameButton)
                        .addGap(11, 11, 11)
                        .addComponent(editSaveGameButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveGameChangesButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deleteStatsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editStatsButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(statsScoreText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveStatsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserButtonActionPerformed
     UserDataHandler.DeleteUserDataFile(selectedUser.userName);
     
     createUserList();
     userNameText.setText("");
     passwordText.setText("");
     dateText.setText("");
    AModText.setText("");
    BModText.setText("");
     statsScoreText.setText("");
     dateText.setEnabled(false);
    AModText.setEnabled(false);
    BModText.setEnabled(false);
    statsScoreText.setEnabled(false);
    deleteUserButton.setEnabled(false);
       editUserButton.setEnabled(false);
     gameListModel.clear();
     statsListModel.clear();
    }//GEN-LAST:event_deleteUserButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       GUIManager.getGUIManager().ReplacePanel(new LoginPanel(), 400, 300);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void userJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userJListValueChanged
        if(userJList.getSelectedIndex()!=-1){
        selectedUser=UserDataHandler.GetUserData((String)userJList.getSelectedValue());
         createGameList();
         createStatsList();
         deleteUserButton.setEnabled(true);
         editUserButton.setEnabled(true);
         userNameText.setText(selectedUser.userName);
         passwordText.setText(String.valueOf(selectedUser.password));
        }
    }//GEN-LAST:event_userJListValueChanged

    private void gameJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_gameJListValueChanged
        if(gameJList.getSelectedIndex()!=-1){  
        selectedGame=UserDataHandler.GetCrossGame(selectedUser,(String)gameJList.getSelectedValue());
         dateText.setValue(selectedGame.stats.startDate.getTime());
         AModText.setText(Integer.toString(selectedGame.stats.A));
         BModText.setText(Integer.toString(selectedGame.stats.B));
         deleteSavedGameButton.setEnabled(true);
         editSaveGameButton.setEnabled(true);
         saveGameChangesButton.setEnabled(false);
        }
    }//GEN-LAST:event_gameJListValueChanged

    private void editUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserButtonActionPerformed
         deleteUserButton.setEnabled(false);
         saveUserButton.setEnabled(true);
         userNameText.setEnabled(true);
         passwordText.setEnabled(true);
    }//GEN-LAST:event_editUserButtonActionPerformed

    private void deleteSavedGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSavedGameButtonActionPerformed
    UserDataHandler.RemoveCrossGame(selectedUser, selectedGame.name);
    UserDataHandler.SaveUserData(selectedUser);
    dateText.setText("");
    AModText.setText("");
    BModText.setText("");
    dateText.setEnabled(false);
    AModText.setEnabled(false);
    BModText.setEnabled(false);
    createGameList();
    }//GEN-LAST:event_deleteSavedGameButtonActionPerformed

    private void editSaveGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveGameButtonActionPerformed
     dateText.setEnabled(true);
     AModText.setEnabled(true);
     BModText.setEnabled(true);
     deleteSavedGameButton.setEnabled(false);
     saveGameChangesButton.setEnabled(true);
    }//GEN-LAST:event_editSaveGameButtonActionPerformed

    private void saveGameChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameChangesButtonActionPerformed
      dateText.setEnabled(false);
      AModText.setEnabled(false);
      BModText.setEnabled(false);
      selectedGame.stats.startDate.setTime((Date)dateText.getValue());
      selectedGame.stats.A=Integer.valueOf(AModText.getText());
      selectedGame.stats.B=Integer.valueOf(BModText.getText());
      UserDataHandler.SaveCrossGame(selectedUser, selectedGame);
      UserDataHandler.SaveUserData(selectedUser);
      deleteSavedGameButton.setEnabled(true);
      saveGameChangesButton.setEnabled(false);
      
    }//GEN-LAST:event_saveGameChangesButtonActionPerformed

    private void statsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_statsJListValueChanged
        if(statsJList.getSelectedIndex()!=-1){
        selectedStats=UserDataHandler.GetSpecificGameStats(selectedUser, (String)statsJList.getSelectedValue());
        statsScoreText.setText(Integer.toString(selectedStats.score));
        deleteStatsButton.setEnabled(true);
        editStatsButton.setEnabled(true);
        }
        
    }//GEN-LAST:event_statsJListValueChanged

    private void saveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserButtonActionPerformed
       UserDataHandler.DeleteUserDataFile(selectedUser.userName);
       selectedUser.userName=userNameText.getText();
       selectedUser.password=passwordText.getPassword();
       UserDataHandler.CreateUser(selectedUser.userName, selectedUser.password);
       createUserList();
       userNameText.setEnabled(false);
       passwordText.setEnabled(false);
       saveUserButton.setEnabled(false);
       deleteUserButton.setEnabled(true);
    }//GEN-LAST:event_saveUserButtonActionPerformed

    private void deleteStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStatsButtonActionPerformed
       UserDataHandler.RemoveSpecificGameStats(selectedUser, selectedStats.gamename);
       UserDataHandler.SaveUserData(selectedUser);
       deleteStatsButton.setEnabled(false);
       editStatsButton.setEnabled(false);
       saveStatsButton.setEnabled(false);
       statsScoreText.setEnabled(false);
       statsScoreText.setText("");
       createStatsList();
    }//GEN-LAST:event_deleteStatsButtonActionPerformed

    private void editStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStatsButtonActionPerformed
      deleteStatsButton.setEnabled(false);
       saveStatsButton.setEnabled(true);
       statsScoreText.setEnabled(true);
    }//GEN-LAST:event_editStatsButtonActionPerformed

    private void saveStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveStatsButtonActionPerformed
      selectedStats.score=Integer.valueOf(statsScoreText.getText());
      UserDataHandler.SaveUserData(selectedUser);
       deleteStatsButton.setEnabled(true);
       saveStatsButton.setEnabled(false);
       statsScoreText.setEnabled(false);
    }//GEN-LAST:event_saveStatsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AModText;
    private javax.swing.JTextField BModText;
    private javax.swing.JFormattedTextField dateText;
    private javax.swing.JButton deleteSavedGameButton;
    private javax.swing.JButton deleteStatsButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JButton editSaveGameButton;
    private javax.swing.JButton editStatsButton;
    private javax.swing.JButton editUserButton;
    private javax.swing.JList gameJList;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton saveGameChangesButton;
    private javax.swing.JButton saveStatsButton;
    private javax.swing.JButton saveUserButton;
    private javax.swing.JList statsJList;
    private javax.swing.JTextField statsScoreText;
    private javax.swing.JList userJList;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables
}
