/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package crosswordgame;

import java.awt.event.ItemEvent;

/**
 *
 * @author Sean
 */
public class GamePanel extends javax.swing.JPanel {
    private crossGraphic cg;
    private javax.swing.JTextArea clues;
    private GUIManager manager;
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        manager=GUIManager.getGUIManager();
        cg=new crossGraphic();
        initComponents();
        jSplitPane1.setRightComponent(cg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsDialog = new javax.swing.JDialog();
        saveExitButton = new javax.swing.JButton();
        showPercentCheck = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        closeOptionsButton = new javax.swing.JButton();
        endGameDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        timeCompLabel = new javax.swing.JLabel();
        finalScoreLabel = new javax.swing.JLabel();
        wordsCompLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        optionsButton = new javax.swing.JButton();
        endTurnButton = new javax.swing.JButton();
        clues=new javax.swing.JTextArea();
        clues.setText(manager.currentGame.getClueList());
        clues.setFocusable(false);
        clues.setEditable(false);
        clues.setLineWrap(true);
        clues.setWrapStyleWord(true);
        jScrollPane1 = new javax.swing.JScrollPane(clues);

        saveExitButton.setText("Save & Exit");
        saveExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExitButtonActionPerformed(evt);
            }
        });

        showPercentCheck.setText("Show # Words Correct");
        showPercentCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                showPercentCheckItemStateChanged(evt);
            }
        });
        showPercentCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPercentCheckActionPerformed(evt);
            }
        });

        jButton1.setText("End Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        closeOptionsButton.setText("Close");
        closeOptionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeOptionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsDialogLayout = new javax.swing.GroupLayout(optionsDialog.getContentPane());
        optionsDialog.getContentPane().setLayout(optionsDialogLayout);
        optionsDialogLayout.setHorizontalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsDialogLayout.createSequentialGroup()
                .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsDialogLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(showPercentCheck))
                    .addGroup(optionsDialogLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(closeOptionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveExitButton, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        optionsDialogLayout.setVerticalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsDialogLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(showPercentCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(saveExitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeOptionsButton)
                .addGap(21, 21, 21))
        );

        jLabel1.setText("Time:");

        jLabel2.setText("Score:");

        jLabel3.setText("Words Complete:");

        jButton2.setText("Return to Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        timeCompLabel.setText("jLabel5");

        finalScoreLabel.setText("jLabel6");

        wordsCompLabel.setText("jLabel7");

        javax.swing.GroupLayout endGameDialogLayout = new javax.swing.GroupLayout(endGameDialog.getContentPane());
        endGameDialog.getContentPane().setLayout(endGameDialogLayout);
        endGameDialogLayout.setHorizontalGroup(
            endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endGameDialogLayout.createSequentialGroup()
                .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(endGameDialogLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeCompLabel)
                            .addComponent(finalScoreLabel)
                            .addComponent(wordsCompLabel)))
                    .addGroup(endGameDialogLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton2)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        endGameDialogLayout.setVerticalGroup(
            endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endGameDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeCompLabel))
                .addGap(18, 18, 18)
                .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(finalScoreLabel))
                .addGap(18, 18, 18)
                .addGroup(endGameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(wordsCompLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setDividerSize(1);

        jSplitPane2.setDividerLocation((int)(getHeight()/10));
        jSplitPane2.setDividerSize(1);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 83));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        optionsButton.setText("Options");
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(optionsButton);

        endTurnButton.setText("End Turn");
        if(manager.currentGame.twoPlayers)
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });
        if(manager.currentGame.twoPlayers)
        jPanel1.add(endTurnButton);

        jSplitPane2.setTopComponent(jPanel1);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jSplitPane2.setRightComponent(jScrollPane1);

        jSplitPane1.setLeftComponent(jSplitPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
        optionsDialog.pack();
        optionsDialog.setLocationRelativeTo(this);
        optionsDialog.setVisible(true);
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void saveExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExitButtonActionPerformed
        if(manager.currentGame.twoPlayers){
        UserDataHandler.SaveCrossGame(manager.currentUser[0], manager.currentGame);
        UserDataHandler.SaveCrossGame(manager.currentUser[1], manager.currentGame);
        UserDataHandler.SaveUserData(manager.currentUser[0]);
        UserDataHandler.SaveUserData(manager.currentUser[1]);
        }
        else{
        UserDataHandler.SaveCrossGame(manager.currentUser[0], manager.currentGame);
        UserDataHandler.SaveUserData(manager.currentUser[0]);
        }
        optionsDialog.setVisible(false);
        manager.ReplacePanel(new MenuPanel(), 400, 300);
    }//GEN-LAST:event_saveExitButtonActionPerformed

    private void showPercentCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_showPercentCheckItemStateChanged
         if(evt.getStateChange()==ItemEvent.DESELECTED)
             cg.showPercent=false;
         if(evt.getStateChange()==ItemEvent.SELECTED)
             cg.showPercent=true;
    }//GEN-LAST:event_showPercentCheckItemStateChanged

    private void closeOptionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeOptionsButtonActionPerformed
        optionsDialog.setVisible(false);
    }//GEN-LAST:event_closeOptionsButtonActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        manager.currentGame.playerTurn=!manager.currentGame.playerTurn;
        clues.setText(manager.currentGame.getClueList());
        cg.repaint();
        
    }//GEN-LAST:event_endTurnButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         optionsDialog.setVisible(false);
         optionsButton.setEnabled(false);
         endTurnButton.setEnabled(false);
         manager.currentGame.isAlive=false;
         manager.currentGame.stats.calculateEndGameData();
         manager.currentGame.stats.user=manager.currentUser[0].userName;
         UserDataHandler.RemoveCrossGame(manager.currentUser[0], manager.currentGame.name);
         UserDataHandler.SaveGameStatistics(manager.currentUser[0], manager.currentGame);
         UserDataHandler.SaveUserData(manager.currentUser[0]);
         if(manager.currentGame.twoPlayers)
         {
            manager.currentGame.stats.user=manager.currentUser[1].userName;
            UserDataHandler.RemoveCrossGame(manager.currentUser[1], manager.currentGame.name);
            UserDataHandler.SaveGameStatistics(manager.currentUser[1], manager.currentGame); 
            UserDataHandler.SaveUserData(manager.currentUser[0]);
         }
         
         timeCompLabel.setText(manager.currentGame.stats.getTimeElapsed(manager.currentGame.stats.endDate));
         finalScoreLabel.setText(Integer.toString(manager.currentGame.stats.score));
         wordsCompLabel.setText(Integer.toString(manager.currentGame.stats.wordComp));
         
         endGameDialog.pack();
         endGameDialog.setLocationRelativeTo(this);
         endGameDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       endGameDialog.dispose();
       manager.ReplacePanel(new MenuPanel(), 400, 300);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showPercentCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPercentCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPercentCheckActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeOptionsButton;
    private javax.swing.JDialog endGameDialog;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JLabel finalScoreLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JButton optionsButton;
    private javax.swing.JDialog optionsDialog;
    private javax.swing.JButton saveExitButton;
    private javax.swing.JCheckBox showPercentCheck;
    private javax.swing.JLabel timeCompLabel;
    private javax.swing.JLabel wordsCompLabel;
    // End of variables declaration//GEN-END:variables
}
