/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package crosswordgame;

import java.util.Arrays;

/**
 *
 * @author Sean
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    
    int player;
    Boolean parameter;
    public Boolean login;
    public LoginPanel() {
        parameter=false;
        player=0;
        initComponents();
    }
    public LoginPanel(int pnum) {
        parameter=true;
        login=false;
        player=pnum;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserDialog = new javax.swing.JDialog();
        createUserB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        newUsernameText = new javax.swing.JTextField();
        newPasswordField = new javax.swing.JPasswordField();
        newConPasswordField = new javax.swing.JPasswordField();
        errorUserLabel = new javax.swing.JLabel();
        errorPassLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        newUserButton = new javax.swing.JButton();
        passwordText = new javax.swing.JPasswordField();
        loginCompText = new javax.swing.JLabel();

        newUserDialog.setResizable(false);
        newUserDialog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                newUserDialogComponentHidden(evt);
            }
        });

        createUserB.setText("Register");
        createUserB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLabel3.setText("Confirm Pasword:");

        newUsernameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newUsernameTextKeyReleased(evt);
            }
        });

        newPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newPasswordFieldKeyReleased(evt);
            }
        });

        newConPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                newConPasswordFieldKeyReleased(evt);
            }
        });

        errorUserLabel.setText(" ");

        errorPassLabel.setText(" ");

        javax.swing.GroupLayout newUserDialogLayout = new javax.swing.GroupLayout(newUserDialog.getContentPane());
        newUserDialog.getContentPane().setLayout(newUserDialogLayout);
        newUserDialogLayout.setHorizontalGroup(
            newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createUserB)
                    .addGroup(newUserDialogLayout.createSequentialGroup()
                        .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newUsernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(newPasswordField)
                            .addComponent(newConPasswordField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorUserLabel)
                            .addComponent(errorPassLabel))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        newUserDialogLayout.setVerticalGroup(
            newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserDialogLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newUsernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorUserLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorPassLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(newConPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createUserB)
                .addContainerGap())
        );

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        newUserButton.setText("New User");
        newUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserButtonActionPerformed(evt);
            }
        });

        loginCompText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginCompText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginCompText, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameText)
                            .addComponent(newUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordText))
                        .addGap(18, 18, 18)
                        .addComponent(loginButton)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginCompText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(userNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(passwordLabel)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(newUserButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        GUIManager manager = GUIManager.getGUIManager();
        if(userNameText.getText().equals("admin") && "123A321".equals(String.valueOf(passwordText.getPassword())) && !parameter){
            manager.ReplacePanel(new AdminPanel(), 400  , 650);
        }
        else{

        manager.currentUser[player]=UserDataHandler.GetUserData(userNameText.getText(), passwordText.getPassword());
        if(manager.currentUser[player]!=null && !parameter){
        loginCompText.setText("Login Complete");
        manager.ReplacePanel(new MenuPanel(),400,300); 
        }
        else if(manager.currentUser[player]!=null && parameter){
            loginCompText.setText("Login Complete");
            login=true; 
        }
        else{
            loginCompText.setText("Login Failed");
        }
        }
        
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void newUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserButtonActionPerformed
        newUserDialog.pack();
        newUserDialog.setLocationRelativeTo(this);
        newUserDialog.setVisible(true);
    }//GEN-LAST:event_newUserButtonActionPerformed

    private void createUserBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBActionPerformed
        Boolean errored=false;
        if(!errorUserLabel.getText().equals("")){
            errorUserLabel.setText("Username Exists");
            errored=true;
        }
        if(!Arrays.equals(newPasswordField.getPassword(),newConPasswordField.getPassword())){
            errorPassLabel.setText("Does not match");
            errored=true;
        }
        if(!errored){
        UserDataHandler.CreateUser(newUsernameText.getText(), newPasswordField.getPassword());
        newUserDialog.setVisible(false);
        }

    }//GEN-LAST:event_createUserBActionPerformed

    private void newUserDialogComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newUserDialogComponentHidden
        errorUserLabel.setText("");
        errorPassLabel.setText("");
        newUsernameText.setText("");
        newPasswordField.setText("");
        newConPasswordField.setText("");
    }//GEN-LAST:event_newUserDialogComponentHidden

    private void newPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newPasswordFieldKeyReleased
        if(Arrays.equals(newPasswordField.getPassword(),newConPasswordField.getPassword())){
            errorPassLabel.setText("");
        }
        else{
            errorPassLabel.setText("Does not match");
        }
    }//GEN-LAST:event_newPasswordFieldKeyReleased

    private void newConPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newConPasswordFieldKeyReleased
        if(Arrays.equals(newPasswordField.getPassword(),newConPasswordField.getPassword())){
            errorPassLabel.setText("");
        }
        else{
            errorPassLabel.setText("Does not match");
        }
    }//GEN-LAST:event_newConPasswordFieldKeyReleased

    private void newUsernameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUsernameTextKeyReleased
        if(!UserDataHandler.CheckUserName(newUsernameText.getText())){
            errorUserLabel.setText("Username exists!");
        }
        else{
            errorUserLabel.setText("");
        }  
    }//GEN-LAST:event_newUsernameTextKeyReleased

    public void loginClear(){
       userNameText.setText(""); 
       passwordText.setText("");
       newUsernameText.setText("");
       newPasswordField.setText("");
       newConPasswordField.setText("");
       loginCompText.setText("");

        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserB;
    private javax.swing.JLabel errorPassLabel;
    private javax.swing.JLabel errorUserLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginCompText;
    private javax.swing.JPasswordField newConPasswordField;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JButton newUserButton;
    private javax.swing.JDialog newUserDialog;
    private javax.swing.JTextField newUsernameText;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField userNameText;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
